### ISSUE TITLE
[Crash] Immediate crash upon attempting to place vertical half slab.

### ISSUE THREAD

**Issue by Gcrusher9000** [Enchanted-Games/enchanted-vertical-slabs#13]
**Describe the crash**
This pack has a lot of mods in it so I am unsure as to which, if any, are causing the incompatibility. The pack was mostly stable, but crashes consistently and immediately upon placing a vertical slab. This is the only vertical slab mod installed and the slab is tagged as coming from this mod. The crash causes the game to instantly stall out to zero frames for about three seconds before crashing to the main title screen for a single frame and then fully crashing Minecraft to desktop. Upon relaunch, the game returns my character and world to the state approximately two seconds before the attempt to place the slab with no observable differences or other effects. 

**Crash log**
Full log is too large for this paste-bin, please see the link below.
While there are quite a number of errors, the pack was running mostly smoothly for hours over multiple sessions before this.

https://mclo.gs/PAinVUn

**To Reproduce**
Steps to reproduce the crash:
1. Craft vertical oak plank slabs.
2. Right click the ground (the top half of another regular slab) with one.
3. Crash happens.

**Additional content**
I could post a video, but it seems it wouldn't add much and a screenshot doesn't add anything.

**Environment**
 - Mod Version: Enchanted Vertical Slabs 1.9.1
 - Mod Loader: Fabric
 - Mod Loader Version: 1.20.1
 - Fabric Api Version: API 0.92.0+1.20.1
 - Launcher: Modrinth (Opens vanilla launcher profile.)

**Comment by Enchanted-Games** [comment]
If possible, can you upgrade enchanted vertical slabs to v2.2 and see if the crash still happens?

**Comment by Ebanuktiy** [comment]
I can confirm the same thing happens on 2.2 with every vertical slab, the moment I place it the game freezes for a few seconds, then goes to Saving World screen and closes. Logs just show what seems almost endless crash message over and over. I also have a lot of mods so tracking down seems hard but at the beginning of the logs where it crashes it says this:
[23:55:07] [CullThread/INFO]:
 [STDERR]: java.lang.StackOverflowError
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844)
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:122)
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844)
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:122)
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844)
[23:55:07] [CullThread/INFO]:
 [STDERR]: 	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:122)
 
 This line repeats a lot, then it shows this:

[23:55:09] [Render thread/WARN]:
 COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[23:55:09] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.StackOverflowError: null
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap.getInt(Object2IntOpenHashMap.java:360) ~[fastutil-8.5.9.jar:?]
	at malte0811.ferritecore.fastmap.FastMap.getKeyFor(FastMap.java:148) ~[ferritecore-6.0.1-fabric.jar:?]
	at malte0811.ferritecore.fastmap.FastMap.getValue(FastMap.java:100) ~[ferritecore-6.0.1-fabric.jar:?]
	at malte0811.ferritecore.fastmap.FastMap.getValue(FastMap.java:110) ~[ferritecore-6.0.1-fabric.jar:?]
	at malte0811.ferritecore.fastmap.immutable.FastMapEntryImmutableMap.get(FastMapEntryImmutableMap.java:24) ~[ferritecore-6.0.1-fabric.jar:?]
	at malte0811.ferritecore.fastmap.immutable.FastMapEntryImmutableMap.get(FastMapEntryImmutableMap.java:10) ~[ferritecore-6.0.1-fabric.jar:?]
	at net.minecraft.class_2688.method_11654(class_2688.java:96) ~[client-intermediary.jar:?]
	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:119) ~[enchanted-vertical-slabs-2.2-fabric-mc1.20.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844) ~[client-intermediary.jar:?]
	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:122) ~[enchanted-vertical-slabs-2.2-fabric-mc1.20.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844) ~[client-intermediary.jar:?]
	at games.enchanted.verticalslabs.block.VerticalSlabBlock.method_9545(VerticalSlabBlock.java:122) ~[enchanted-vertical-slabs-2.2-fabric-mc1.20.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:5844) ~[client-intermediary.jar:?]
	
I have a "Simply Optimized" modpack as a base on top of which I added content mods like Lets Do series, some of furniture etc. Hopefully this is of any use

**Comment by Enchanted-Games** [comment]
i thought i implemented a fix for this at some point, maybe it didn't carry over to v2.
i'll see if i can get it fixed soon!

**Comment by Legacy7K** [comment]
Same happens to me? Can you tell me how you fixed this?
